### ISSUE TITLE
Play button image loads on every hover interaction

### ISSUE THREAD

**Issue by djmtype** [groupboard/ytdefer#1]
Each time you hover over the play button, a new play button image is loaded. Open Devtools, goto the Network tab, then hover over the play button to see how it gets added to the timeline and makes an additional request.

**Comment by djmtype** [comment]
Also, the play button is inaccessible to keyboard focus

**Comment by groupboard** [comment]
When you hover, it changes to the red image and makes one request. If you then move the mouse out and back in again, there are no new requests as it's using the cache. Are you seeing any different behaviour? Moving the other issue to a separate bug.

**Comment by djmtype** [comment]
@groupboard Look at the [screencast](https://cloudup.com/cAMQHegBhLN) and pay attention to the number of requests and timeline. Each time I hover in/out of the video,  it makes a new request for the same black and red buttons.

**Comment by groupboard** [comment]
It doesn't do that for me, and there is no reason why it should...that image should be cached. Have you turned off your cache?
