### ISSUE TITLE
ADA WCAG 2.1 AA issue

### ISSUE THREAD

**Issue by POOLEworks** [groupboard/ytdefer#6]
**Here's what I'm dealing with.**
And I apologize for the irrational crazy demands that the ADA creates. The image now has an alt tag. The overall link has a title. 
_This is getting called out now:_

> This button element is empty and has no programmatically determined name.
> 
> A programmatically determined name allows screen readers to tell the user what the control does. To add a name do one of the following:
> 	•	Add text between the BUTTON start and end tags
> 	•	Add a TITLE attribute
> 	•	Add an ARIA-LABELLEDBY attribute (not supported in all screen readers)
> 	•	Add an ARIA-LABEL attribute (not supported in all screen readers)
> 
> Here's the created button:
<  button id="ytdefer_icon0" style= "background-image: url(&quot;data:image/svg+xml;base64, <<< Shortened >>> ;); position: absolute; border: 0px; background-color: transparent; left: 110px; top: 56.5px; width: 73px; height: 52px; pointer-events: none;"></  button  >
 
I'd like to throw a title attribute in there.
Thanks!
`

**Comment by groupboard** [comment]
Ok, thanks. I've updated it to add an aria-label of "Play" to the button (which is the same as YouTube).

**Comment by POOLEworks** [comment]
Henri, I see where you added it to the code but it's not getting into the final output.

```
<script src="inc/ytdefer.min.js"></script>
<div class="ytdefer embed-responsive embed-responsive-16by9 martop18" title="ABC News Special Report on   San Diego" data-alt="Our   video screenshot" data-title=
"ABC News Special Report on BlueVault San Diego" data-src="4HaPcpBsYsM">
 <div id="ytdefer_vid0" style="width: 360px; height: 203px; position: relative;">
  <img alt="Our   video screenshot" title="ABC News Special Report on   San Diego" src="https://img.youtube.com/vi/4HaPcpBsYsM/0.jpg" id="ytdefer_img0" style=
  "width: 100%; height: 100%; object-fit: cover; position: absolute;">

```

> Priority 1 This button element is empty and has no programmatically determined name.
> A programmatically determined name allows screen readers to tell the user what the control does. To add a name do one of the following:
> Add text between the BUTTON start and end tags
> Add a TITLE attribute
> Add an ARIA-LABELLEDBY attribute (not supported in all screen readers)
> Add an ARIA-LABEL attribute (not supported in all screen readers)
> Line 1686 WCAG 2.0 A F68
> 

```
<button id="ytdefer_icon0" style=
  "background-image: url(&quot;data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjEwMCUiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmlld0JveD0iMCAwIDY4IDQ4IiB3aWR0aD0iMTAwJSI+PHBhdGggY2xhc3M9Inl0cC1sYXJnZS1wbGF5LWJ1dHRvbi1iZyIgZD0iTTY2LjUyLDcuNzRjLTAuNzgtMi45My0yLjQ5LTUuNDEtNS40Mi02LjE5QzU1Ljc5LC4xMywzNCwwLDM0LDBTMTIuMjEsLjEzLDYuOSwxLjU1IEMzLjk3LDIuMzMsMi4yNyw0LjgxLDEuNDgsNy43NEMwLjA2LDEzLjA1LDAsMjQsMCwyNHMwLjA2LDEwLjk1LDEuNDgsMTYuMjZjMC43OCwyLjkzLDIuNDksNS40MSw1LjQyLDYuMTkgQzEyLjIxLDQ3Ljg3LDM0LDQ4LDM0LDQ4czIxLjc5LTAuMTMsMjcuMS0xLjU1YzIuOTMtMC43OCw0LjY0LTMuMjYsNS40Mi02LjE5QzY3Ljk0LDM0Ljk1LDY4LDI0LDY4LDI0UzY3Ljk0LDEzLjA1LDY2LjUyLDcuNzR6IiBmaWxsPSIjMjEyMTIxIiBmaWxsLW9wYWNpdHk9IjAuOCI+PC9wYXRoPjxwYXRoIGQ9Ik0gNDUsMjQgMjcsMTQgMjcsMzQiIGZpbGw9IiNmZmYiPjwvcGF0aD48L3N2Zz4=&quot;); position: absolute; border: 0px; background-color: transparent; left: 143.5px; top: 75.5px; width: 73px; height: 52px; pointer-events: none;"></button>
 </div>
</div>
<script>
window.addEventListener('load', ytdefer_setup);
</script>
```

**Comment by groupboard** [comment]
Perhaps your browser has cached the old js? The aria-label is definitely there. You can see an example at www.groupboard.com.
